// Bundles main, preload and renderer with esbuild. Flags: --tests, --eval.
import { build } from "esbuild";
import { cpSync, mkdirSync } from "node:fs";
import { readFileSync, writeFileSync } from "node:fs";

const args = new Set(process.argv.slice(2));
const common = { bundle: true, sourcemap: true, logLevel: "warning", loader: { ".md": "text" } };

if (args.has("--tests")) {
  await build({ ...common, entryPoints: ["src/**/*.test.ts"], outdir: "dist-tests", platform: "node", format: "cjs", target: "node22" });
  process.exit(0);
}
if (args.has("--eval")) {
  await build({ ...common, entryPoints: ["evals/run-eval.ts"], outdir: "dist-eval", platform: "node", format: "cjs", target: "node22" });
  process.exit(0);
}

mkdirSync("dist", { recursive: true });
await build({ ...common, entryPoints: ["src/main/main.ts"], outfile: "dist/main.js", platform: "node", format: "cjs", target: "node22", external: ["electron"] });
await build({ ...common, entryPoints: ["src/main/preload.ts"], outfile: "dist/preload.js", platform: "node", format: "cjs", target: "node22", external: ["electron"] });
await build({ ...common, entryPoints: ["src/renderer/overlay.ts", "src/renderer/settings.ts", "src/renderer/feedback.ts"], outdir: "dist/renderer", platform: "browser", format: "esm", target: "chrome130" });
await build({ ...common, entryPoints: ["src/renderer/pcm-worklet.ts"], outfile: "dist/renderer/pcm-worklet.js", platform: "browser", format: "esm", target: "chrome130", sourcemap: false });
for (const f of ["overlay.html", "settings.html", "feedback.html", "style.css"]) cpSync(`src/renderer/${f}`, `dist/renderer/${f}`);

// Inter variable font (SIL OFL 1.1, from @fontsource-variable/inter), latin + latin-ext, normal style.
// Local files, so the pages' CSP (default-src 'self') allows them.
// A page opts in with <link rel="stylesheet" href="fonts.css"> and font-family "Inter Variable".
{
  const fontPkg = "node_modules/@fontsource-variable/inter";
  const fontCss = readFileSync(`${fontPkg}/wght.css`, "utf8");
  mkdirSync("dist/renderer/fonts", { recursive: true });
  const faces = ["latin-ext", "latin"].map((subset) => {
    const file = `inter-${subset}-wght-normal.woff2`;
    cpSync(`${fontPkg}/files/${file}`, `dist/renderer/fonts/${file}`);
    const range = fontCss.match(new RegExp(`inter-${subset}-wght-normal \\*/[^}]*unicode-range:\\s*([^;]+);`))?.[1];
    return [
      "@font-face {",
      '  font-family: "Inter Variable";',
      "  font-style: normal;",
      "  font-display: swap;",
      "  font-weight: 100 900;",
      `  src: url("fonts/${file}") format("woff2");`,
      ...(range ? [`  unicode-range: ${range.trim()};`] : []),
      "}",
    ].join("\n");
  });
  cpSync(`${fontPkg}/LICENSE`, "dist/renderer/fonts/LICENSE-Inter.txt");
  writeFileSync("dist/renderer/fonts.css", `/* Inter Variable, SIL Open Font License 1.1 (see fonts/LICENSE-Inter.txt). Generated by scripts/build.mjs. */\n${faces.join("\n\n")}\n`);
}
